deploy-prod:
  stage: deploy

  only:
    - master

  tags:
    - master

  script:
    - cp -r -u * $ASNL_BACKEND
    - cd $ASNL_BACKEND
    - npm install
    - npm run build
    - pm2 restart asnl
    - service apache2 restart
