deploy-prod:
  stage: deploy

  only: 
    - master
  
  tags:
    - master

  script:
    - cp -r -u * $ASNL_BACKEND
    - cd $ASNL_BACKEND
    - npm install
    - pm2 restart ./dist/index.js
    - service nginx restart
    